---
- name: Install Vagrant
  become: true
  package:
    name: vagrant
    state: latest
  when: 
    - "'vagrant' not in ansible_facts.packages"

- block:
  - name: Get kubectl last stable version
    shell: curl -L -s https://dl.k8s.io/release/stable.txt
    register: kubectl_version

  - name: Download kubectl binaries
    shell: "curl -LO 'https://dl.k8s.io/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl'"

  - name: Install kubectl
    shell: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    become: true

  - name: Kubectl binaries cleanup
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - kubectl
      - kubectl.sha256
  when: kubectl_installed.rc != 0

- block:
  - name: Download VirtualBox for Ubuntu
    get_url:
      url: "{{ vbox_ubuntu }}"
      dest: /tmp/
    register: vbox_pkg
  
  - name: Install VirtualBox
    apt:
      deb: "{{ vbox_pkg.dest }}"
  become: true
  when: 
    - "'virtualbox' not in ansible_facts.packages | lower"